image: python:3.6

before_script:
  - python --version ; pip --version # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
    - pip install -r requirements.txt
    - pip install -e .
    - pytest
